import type { LangCode } from '@/types';

/** UI-chrome text for the published reader (menus, search, welcome screen, etc.), keyed
 *  by language. Folio/section content is translated separately via the *I18n fields on
 *  Project/Section/Folio — this table only covers the fixed reader shell. Add a language
 *  by adding a row here (and to src/lib/languages.ts); an unlisted language falls back to
 *  Spanish at read time (see S() in buildGuide.ts's RUNTIME). */
export const READER_STRINGS: Record<LangCode, Record<string, string>> = {
  es: {
    menu: 'Menú',
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Oscuro',
    themeAuto: 'Auto',
    textSize: 'Texto',
    shrink: 'Achicar',
    grow: 'Agrandar',
    resetSize: 'Tamaño normal',
    viewMode: 'Vista',
    viewGuided: 'Guiada',
    viewClean: 'Limpia',
    langLabel: 'Idioma',
    misc: 'Varios',
    help: 'Ayuda',
    about: 'Acerca de…',
    install: 'Instalar en el dispositivo',
    aboutTitle: 'Acerca de',
    aboutUpdated: 'Última actualización',
    checkUpdates: 'Comprobar actualizaciones',
    updateNow: 'Actualizar',
    checking: 'Comprobando…',
    checkFailed: 'No se pudo comprobar. ¿Estás sin conexión?',
    upToDate: 'Ya tienes la última versión.',
    newVersionAvailable: 'Hay una versión nueva.',
    index: 'Índice',
    history: 'Historial',
    favorites: 'Favoritos',
    session: 'Sesión',
    clear: 'Limpiar',
    search: 'Buscar',
    clearSearch: 'Limpiar búsqueda',
    noResultsTitle: 'Sin resultados',
    noResultsBody: 'No se encontró nada con esas palabras.',
    result: 'resultado',
    results: 'resultados',
    moveUp: '↑ Mover arriba',
    moveDown: '↓ Mover abajo',
    noColor: 'Sin color',
    options: 'Opciones',
    favEmptyInFolio: 'Aún no has marcado ningún folio. Usa el botón de abajo para añadir este.',
    favEmptyGeneral: 'Aún no has marcado ningún folio. Entra en uno y usa el botón de este panel.',
    favRemove: '★ Quitar de favoritos',
    favAdd: '☆ Marcar como favorito',
    favorite: 'Favorito',
    home: '⌂ Inicio',
    appendices: 'Apéndices',
    untitled: '(sin título)',
    folioFallback: 'Folio',
    sectionFallback: 'Sección',
    prev: 'Anterior',
    next: 'Siguiente',
    linkGo: 'Ir',
    folio: 'folio',
    folios: 'folios',
    welcomeIntro: '¡Hola! Bienvenido/a a la guía para analistas de conciencia.',
    welcomeQuestion: '¿Cómo te llamás?',
    welcomeNamePlaceholder: 'Tu nombre',
    welcomeContinue: 'Continuar',
    welcomeHello: '¡Hola, {name}!',
    iosInstallMsg: 'Añade esta guía a tu pantalla de inicio: pulsa <b>Compartir</b> y luego <b>«Añadir a pantalla de inicio»</b>.',
    iosInstallClose: 'Cerrar',
    guideFallback: 'Guía',
    dateLocale: 'es-ES',
  },
  en: {
    menu: 'Menu',
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeAuto: 'Auto',
    textSize: 'Text',
    shrink: 'Shrink',
    grow: 'Enlarge',
    resetSize: 'Normal size',
    viewMode: 'View',
    viewGuided: 'Guided',
    viewClean: 'Clean',
    langLabel: 'Language',
    misc: 'More',
    help: 'Help',
    about: 'About…',
    install: 'Install on device',
    aboutTitle: 'About',
    aboutUpdated: 'Last updated',
    checkUpdates: 'Check for updates',
    updateNow: 'Update',
    checking: 'Checking…',
    checkFailed: 'Could not check. Are you offline?',
    upToDate: 'You already have the latest version.',
    newVersionAvailable: 'A new version is available.',
    index: 'Index',
    history: 'History',
    favorites: 'Favorites',
    session: 'Session',
    clear: 'Clear',
    search: 'Search',
    clearSearch: 'Clear search',
    noResultsTitle: 'No results',
    noResultsBody: 'Nothing found for those words.',
    result: 'result',
    results: 'results',
    moveUp: '↑ Move up',
    moveDown: '↓ Move down',
    noColor: 'No color',
    options: 'Options',
    favEmptyInFolio: "You haven't bookmarked any folio yet. Use the button below to add this one.",
    favEmptyGeneral: "You haven't bookmarked any folio yet. Open one and use the button in this panel.",
    favRemove: '★ Remove from favorites',
    favAdd: '☆ Add to favorites',
    favorite: 'Favorite',
    home: '⌂ Home',
    appendices: 'Appendices',
    untitled: '(untitled)',
    folioFallback: 'Folio',
    sectionFallback: 'Section',
    prev: 'Previous',
    next: 'Next',
    linkGo: 'Go',
    folio: 'folio',
    folios: 'folios',
    welcomeIntro: 'Hello! Welcome to the guide for consciousness analysts.',
    welcomeQuestion: "What's your name?",
    welcomeNamePlaceholder: 'Your name',
    welcomeContinue: 'Continue',
    welcomeHello: 'Hello, {name}!',
    iosInstallMsg: 'Add this guide to your home screen: tap <b>Share</b> and then <b>“Add to Home Screen”</b>.',
    iosInstallClose: 'Close',
    guideFallback: 'Guide',
    dateLocale: 'en-GB',
  },
  de: {
    menu: 'Menü',
    theme: 'Thema',
    themeLight: 'Hell',
    themeDark: 'Dunkel',
    themeAuto: 'Auto',
    textSize: 'Text',
    shrink: 'Verkleinern',
    grow: 'Vergrößern',
    resetSize: 'Normale Größe',
    viewMode: 'Ansicht',
    viewGuided: 'Geführt',
    viewClean: 'Einfach',
    langLabel: 'Sprache',
    misc: 'Mehr',
    help: 'Hilfe',
    about: 'Über…',
    install: 'Auf Gerät installieren',
    aboutTitle: 'Über',
    aboutUpdated: 'Letzte Aktualisierung',
    checkUpdates: 'Nach Updates suchen',
    updateNow: 'Aktualisieren',
    checking: 'Wird geprüft…',
    checkFailed: 'Konnte nicht geprüft werden. Bist du offline?',
    upToDate: 'Du hast bereits die neueste Version.',
    newVersionAvailable: 'Es ist eine neue Version verfügbar.',
    index: 'Verzeichnis',
    history: 'Verlauf',
    favorites: 'Favoriten',
    session: 'Sitzung',
    clear: 'Löschen',
    search: 'Suchen',
    clearSearch: 'Suche löschen',
    noResultsTitle: 'Keine Ergebnisse',
    noResultsBody: 'Für diese Wörter wurde nichts gefunden.',
    result: 'Ergebnis',
    results: 'Ergebnisse',
    moveUp: '↑ Nach oben',
    moveDown: '↓ Nach unten',
    noColor: 'Keine Farbe',
    options: 'Optionen',
    favEmptyInFolio: 'Du hast noch kein Folio markiert. Nutze den Button unten, um dieses hinzuzufügen.',
    favEmptyGeneral: 'Du hast noch kein Folio markiert. Öffne eines und nutze den Button in diesem Panel.',
    favRemove: '★ Aus Favoriten entfernen',
    favAdd: '☆ Zu Favoriten hinzufügen',
    favorite: 'Favorit',
    home: '⌂ Start',
    appendices: 'Anhänge',
    untitled: '(ohne Titel)',
    folioFallback: 'Folio',
    sectionFallback: 'Abschnitt',
    prev: 'Zurück',
    next: 'Weiter',
    linkGo: 'Los',
    folio: 'Folio',
    folios: 'Folios',
    welcomeIntro: 'Hallo! Willkommen beim Leitfaden für Bewusstseinsanalytiker.',
    welcomeQuestion: 'Wie heißt du?',
    welcomeNamePlaceholder: 'Dein Name',
    welcomeContinue: 'Weiter',
    welcomeHello: 'Hallo, {name}!',
    iosInstallMsg: 'Füge diesen Leitfaden zu deinem Startbildschirm hinzu: tippe auf <b>Teilen</b> und dann auf <b>„Zum Home-Bildschirm“</b>.',
    iosInstallClose: 'Schließen',
    guideFallback: 'Leitfaden',
    dateLocale: 'de-DE',
  },
};
